name: Scientific Data Lab
on: [push, pull_request]

jobs:
  actions:
    runs-on: ubuntu-18.04
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag sdlab .
    - name: revisa el estilo
      run: docker run sdlab make check